services:
  api-gateway:
    build:
      args:
        - executable=ApiGateway/executable.jar
  authentication-service:
    build:
      args:
        - executable=AuthenticationService/executable.jar
  metrics:
    build:
      args:
        - executable=Metrics/executable.jar
  ebikes:
    build:
      args:
        - executable=EBikes/executable.jar
  users:
    build:
      args:
        - executable=Users/executable.jar
  rides:
    build:
      args:
        - executable=Rides/executable.jar

networks:
  private_network:
    driver: bridge
