services:
  api-gateway:
    build:
      args:
        - executable=ApiGateway/executable.jar
    ports:
      - 8080:8080
    networks:
      - private_network
  authentication:
    build:
      args:
        - executable=Authentication/executable.jar
    networks:
      - private_network
  metrics:
    build:
      args:
        - executable=Metrics/executable.jar
    networks:
      - private_network
  ebikes:
    build:
      args:
        - executable=EBikes/executable.jar
    networks:
      - private_network
  users:
    build:
      args:
        - executable=Users/executable.jar
    networks:
      - private_network
  rides:
    build:
      args:
        - executable=Rides/executable.jar
    networks:
      - private_network

networks:
  private_network:
    driver: bridge
