services:
  api-gateway:
    build:
      args:
        - executable=ApiGateway/executable.jar
    ports:
      - 8080:8080
    networks:
      - private_network
  authentication:
    build:
      args:
        - executable=Authentication/executable.jar
    networks:
      - private_network
      - authentication_network
    environment:
      SERVICES_USERS_ADDRESS: http://users:8080
      JWT_SIGNING_SECRET: ${JWT_SIGNING_SECRET?}
      JWT_EXPIRATION_SECONDS: 900 # 15 minutes
      MYSQL_HOST: authentication-db
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: authentication-db
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?}
      MYSQL_USER: ${MYSQL_USER?}
    depends_on:
      authentication-db:
        condition: service_healthy
  authentication-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: authentication-db
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?}
      MYSQL_USER: ${MYSQL_USER?}
    networks:
      - authentication_network
    healthcheck:
      test: mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD --execute "SHOW DATABASES;"
      start_period: 20s 
      start_interval: 1s
      interval: 60s
      timeout: 2s
      retries: 5
  metrics:
    build:
      args:
        - executable=Metrics/executable.jar
    networks:
      - private_network
  ebikes:
    build:
      args:
        - executable=EBikes/executable.jar
    networks:
      - private_network
  users:
    build:
      args:
        - executable=Users/executable.jar
    networks:
      - private_network
  rides:
    build:
      args:
        - executable=Rides/executable.jar
    networks:
      - private_network

networks:
  private_network:
    driver: bridge
  authentication_network:
    driver: bridge
