services:
  api-gateway:
    ports:
      - 8080:8080
  ebikes:
    volumes:
      - ${HOME}/Desktop/EBikeApp/db:/data/db:rw
    ports:
      - 8081:8080
  users:
    volumes:
      - ${HOME}/Desktop/EBikeApp/db:/data/db:rw
    ports:
      - 8082:8080
  rides:
    volumes:
      - ${HOME}/Desktop/EBikeApp/db:/data/db:rw
    ports:
      - 8083:8080
  authentication:
    ports:
      - 8084:8080
  authentication-db:
    volumes:
      - ${HOME}/Desktop/EBikeApp/auth/mysql:/var/lib/mysql
  metrics:
    volumes:
      - ${HOME}/Desktop/EBikeApp/db:/data/db:rw
    ports:
      - 8085:8080
