x-common_environment: &common_environment
  APIGATEWAY_SERVICE_ADDRESS: api-gateway:8080
  AUTHENTICATION_SERVICE_ADDRESS: authentication:8080
  METRICS_SERVICE_ADDRESS: metrics:8080
  EBIKES_SERVICE_ADDRESS: ebikes:8080
  USERS_SERVICE_ADDRESS: users:8080
  RIDES_SERVICE_ADDRESS: rides:8080

x-common_healthcheck: &common_healthcheck
  healthcheck:
    test: curl --fail localhost:8080/healthCheck || exit 1
    start_period: 20s
    start_interval: 1s
    interval: 60s
    timeout: 5s
    retries: 2
  restart: unless-stopped
  
services:
  api-gateway:
    build:
      args:
        - executable=ApiGateway/executable.jar
    ports:
      - 8080:8080
    environment:
      <<: *common_environment
    networks:
      - private_network
    <<: *common_healthcheck

  authentication:
    build:
      args:
        - executable=Authentication/executable.jar
    networks:
      - private_network
      - authentication_network
    environment:
      <<: *common_environment
      JWT_SIGNING_SECRET: ${JWT_SIGNING_SECRET?}
      JWT_EXPIRATION_SECONDS: 900 # 15 minutes
      MYSQL_HOST: authentication-db
      MYSQL_PORT: 3306
      MYSQL_DB_NAME: authentication-db
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?}
      MYSQL_USER: ${MYSQL_USER?}
    depends_on:
      authentication-db:
        condition: service_healthy
    <<: *common_healthcheck

  authentication-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: authentication-db
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?}
      MYSQL_USER: ${MYSQL_USER?}
    networks:
      - authentication_network
    healthcheck:
      test: mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD --execute "SHOW DATABASES;"
      start_period: 20s
      start_interval: 1s
      interval: 60s
      timeout: 2s
      retries: 5

  metrics:
    build:
      args:
        - executable=Metrics/executable.jar
    networks:
      - private_network
    environment:
      <<: *common_environment
    healthcheck:
      test: curl --fail localhost:8080/metrics/counters/none || exit 1
      start_period: 20s
      start_interval: 1s
      interval: 5s
      timeout: 5s
      retries: 2
    restart: unless-stopped

  ebikes:
    build:
      args:
        - executable=EBikes/executable.jar
    networks:
      - private_network
    environment:
      <<: *common_environment
    <<: *common_healthcheck

  users:
    build:
      args:
        - executable=Users/executable.jar
    networks:
      - private_network
    environment:
      <<: *common_environment
    <<: *common_healthcheck

  rides:
    build:
      args:
        - executable=Rides/executable.jar
    networks:
      - private_network
    environment:
      <<: *common_environment
    <<: *common_healthcheck

networks:
  private_network:
    driver: bridge
  authentication_network:
    driver: bridge
