@startuml components

left to right direction

component "User frontend" as UserFE <<Client>>
component "Admin frontend" as AdminFE <<Client>>

component Backend <<Server>> {
    component "API Gateway" as APIGateway <<Microservice>>

    rectangle "Private Network" {
        component "EBikes" as EBikes <<Microservice>>
        interface "EBikes API" as EBikesAPI
        APIGateway --( EBikesAPI
        EBikes -u-() EBikesAPI

        component "Users" as Users <<Microservice>>
        interface "Users API" as UsersAPI
        APIGateway --( UsersAPI
        Users -u-() UsersAPI
        Users -u-() UserAuthAPI

        component "Rides" as Rides <<Microservice>>
        interface "Rides API" as RidesAPI
        APIGateway --( RidesAPI
        Rides -u-() RidesAPI
        Rides --( UsersAPI
        Rides --( EBikesAPI

        component "Authentication Server" as AuthServer <<Microservice>>
        interface "Authentication API" as AuthAPI
        APIGateway --( AuthAPI
        AuthServer -u-() AuthAPI

        interface "Users Authentication API" as UserAuthAPI
        AuthServer --( UserAuthAPI
    }
}

APIGateway -u-() "API Gateway API"
UserFE --( "API Gateway API"
AdminFE --( "API Gateway API"

@enduml