@startuml metrics-service-domain-model

struct Label {
    value: String
}

class Measurement {
    timestamp: DateTime
}

Measurement "0..*" -- "1..*" Label

struct Endpoint {
    name: String
    healthCheckUrl: URL
}

class Metrics <<Service>> {
    addMeasurement(measurement: Measurement): Void
    measurements(lables: Seq<Label>)
}

Metrics "1" o-- "0..*" Endpoint : "monitors >"
Metrics "1" o-- "0..*" Measurement

hide empty members

@enduml
