@startuml Users-users-components

title "Users microservice"

left to right direction

component "DB"
interface "Users API" as UsersAPI

hexagon Adapters {
    hexagon Domain as DomainHex {
        component Domain {
            portout "Repository\n<Users>" as Repo

        }
    }

    component "Repository Adapter" as RepoAdapter
    RepoAdapter -u-|> Repo
    RepoAdapter -l-> DB

    component "HTTPPresentationAdapter" as HTTPAdapter
    HTTPAdapter -d-> Domain : uses
    HTTPAdapter -l-() UsersAPI
}

@enduml
