@startuml users-components

title "Users microservice"

left to right direction

component "DB"
interface "Users API" as UsersAPI
interface "Users Authentication API" as UsersAuthAPI
interface "Collect Metrics API" as CollectMetricsAPI

hexagon Adapters {
    hexagon Domain as DomainHex {
        component Domain {
            portout "UsersRepository" as Repo
            portout MetricsService
            portin UsersService
        }
    }

    component "Repository Adapter" as RepoAdapter
    RepoAdapter -u-|> Repo
    RepoAdapter -l-> DB

    component "Metrics Service Adapter" as MetricsAdapter
    MetricsAdapter -u-|> MetricsService
    MetricsAdapter -r-( CollectMetricsAPI

    component "HTTPPresentationAdapter" as HTTPAdapter
    HTTPAdapter -d-> UsersService
    HTTPAdapter -() UsersAPI
    HTTPAdapter -() UsersAuthAPI
    ' just for layout
    UsersAPI -[hidden]-> UsersAuthAPI
}

component "Metrics Service" as MetricsService <<Microservice>>
MetricsService -r-() CollectMetricsAPI

@enduml
