@startuml users-microservice-domain-model

title Users microservice domain model

class User {
    credit: Credit
}
struct Username {
    value: String
}
User "1" -u-> "id 1" Username

class UsersRepository <<Repository>>
UsersRepository o-l- User

class UsersService <<Service>> {
    checkCredit(username: Username): Credit
    rechargeCredit(username: Username, rechargeAmount: Credit): Credit
    ..
    healthCheck(): Void
}

UsersService --> UsersRepository : "uses"

class MetricsService <<Service>>
UsersService --> MetricsService : "uses"

@enduml
