name: Build diagrams
on: push

jobs:

  build-diagrams:
    name: Build diagrams
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged
        ports:
          - 2375:2375

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build diagrams
        run: 'docker run -v $(pwd):/data plantuml/plantuml:1.2024 -v -o .. /data/doc/diagrams/src'
      - uses: stefanzweifel/git-auto-commit-action@v5 # commiting if something changed
